// Generated by CoffeeScript 1.4.0
(function() {
  var app, dbPedia, express, mongoDB, personFinder;

  express = require('express');

  dbPedia = require('./server/dbPediaScraper');

  mongoDB = require('./server/mongoDBConnector');

  personFinder = require('./server/personFinder');

  app = express();

  app.get('/dbpedia', function(req, res) {
    return mongoDB.getPerson(req.query['wikipage'], function(err, mongoResults) {
      console.log(mongoResults);
      if (mongoResults) {
        return res.send(mongoResults);
      } else {
        return dbPedia.getJSON(req.query["wikipage"], function(data) {
          return mongoDB.addPerson(data, function() {
            return res.send(data);
          });
        });
      }
    });
  });

  app.use("/", express["static"](__dirname + '/client'));

  app.get('/wikipedia', function(req, res) {
    return personFinder.getAllLinks(req.query['wikipage'], function(err, data) {
      console.log("Wiki data: " + data);
      return res.send(data);
    });
  });

  app.listen(process.env.PORT);

}).call(this);
