// Generated by CoffeeScript 1.4.0
(function() {
  var app, dbPedia, express, mongoDB;

  express = require('express');

  dbPedia = require('./server/dbPediaScraper');

  mongoDB = require('./server/mongoDBConnector');

  app = express();

  app.get('/dbpedia', function(req, res) {
    return mongoDB.getPerson(req.query['wikipage'], function(err, mongoResults) {
      console.log(mongoResults);
      if (mongoResults) {
        return res.send(mongoResults);
      } else {
        return dbPedia.getJSON(req.query["wikipage"], function(data) {
          return mongoDB.addPerson(data, function() {
            return res.send(data);
          });
        });
      }
    });
  });

  app.use("/", express["static"](__dirname + '/client'));

  app.listen(3000);

  console.log("Listening on port 3000");

}).call(this);
