// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, mongoDB;

  express = require('express');

  mongoDB = require('./server/mongoDBConnector');

  app = express();

  app.get('/getPerson', function(req, res) {
    return mongoDB.getPerson(req.query['wikipage'], function(err, mongoResults) {
      console.log("Mongo Results", mongoResults);
      if (mongoResults) {
        return res.send(mongoResults);
      } else {
        return res.send("Not In DB");
      }
    });
  });

  app.use("/updatePerson", function(req, res) {
    var relations;
    relations = JSON.parse(req.headers.relations);
    console.log(relations);
    return mongoDB.updatePersonRelations(req.query['name'], relations(function() {
      return console.log("Added Relations to db");
    }));
  });

  app.use('/savePerson', function(req, res) {
    var newPerson;
    newPerson = {
      name: req.query["name"],
      dob: req.query["dob"],
      url: "http://en.wikipedia.org/" + req.query["name"],
      relations: req.query["relations"]
    };
    return mongoDB.addPerson(newPerson, function(error) {
      return res.send("stored in DB, error: " + error);
    });
  });

  app.use("/", express["static"](__dirname + '/client'));

  app.get('/wikipedia', function(req, res) {
    return personFinder.getAllLinks(req.query['wikipage'], function(err, data) {
      console.log("Wiki data: " + data);
      return res.send(data);
    });
  });

  app.listen(process.env.PORT);

}).call(this);
