// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    return $('.nameInput').on("keyup", function(event) {
      var scraper;
      if (event.keyCode === 13) {
        scraper = makeScraper();
        return scraper.getRelatedPeople(event.target.value);
      }
    });
  });

}).call(this);
