// Generated by CoffeeScript 1.4.0
(function() {
  var makeScraper;

  makeScraper = function() {
    var scraper;
    scraper = {
      getRelatedPeople: function(person) {},
      checkIfPerson: function(link) {}
    };
    return scraper;
  };

}).call(this);
