// Generated by CoffeeScript 1.4.0
(function() {
  var assert;

  assert = require("assert");

  describe('Parser', function() {
    return describe('.parse()', function() {
      return it('should return correctly formatted dates', function() {
        return assert(1 === 1);
      });
    });
  });

}).call(this);
