// Generated by CoffeeScript 1.4.0
(function() {
  var assert, parser, sampleData;

  assert = require("assert");

  parser = require("../../js/server/parser");

  sampleData = require("./sampleData");

  describe('Parser', function() {
    return describe('.parse()', function() {
      return it('should return correctly formatted dates', function() {
        return assert(1 === 1);
      });
    });
  });

}).call(this);
