// Generated by CoffeeScript 1.4.0
(function() {
  var assert;

  assert = require('chai').assert;

  describe('personModel', function() {
    return describe('.makePerson()', function() {
      return it('should return correctly formatted dates', function() {
        return assert.equal(1, 1, "One equals 1");
      });
    });
  });

}).call(this);
