// Generated by CoffeeScript 1.4.0
var assert, requirejs;

assert = require('chai').assert;

requirejs = require('requirejs');

requirejs.config({
  nodeRequire: require
});

requirejs(['../client/getPerson'], function(getPerson) {
  return describe('getPerson', function() {
    return describe('getPerson.getPerson', function() {
      return getPerson.getPerson("Jesus", function() {
        return console.log("The Test Worked");
      });
    });
  });
});
