// Generated by CoffeeScript 1.4.0

require(["findBirth", "graph", "typeAhead", "getPerson"], function(findBirth, graph, typeAhead, getPerson) {
  return $(document).ready(function() {
    typeAhead.attachWikiAutoComplete(".nameInput");
    $('.nameInput').on("keyup", function(event) {
      if (event.keyCode === 13) {
        return $('.findBirthDate').click();
      }
    });
    return $('.findBirthDate').on("click", function(event) {
      var searchName;
      searchName = $(".nameInput").val();
      return getPerson.getPerson(searchName);
    });
  });
});
