// Generated by CoffeeScript 1.4.0
(function() {
  var personTest;

  personTest = null;

  $(document).ready(function() {
    return $('.nameInput').on("keyup", function(event) {
      var settings;
      if (event.keyCode === 13) {
        settings = {
          url: "/dbpedia/?wikipage=" + event.target.value,
          dataType: "json",
          success: function(data) {
            return personTest = data;
          },
          error: function(err) {
            return console.log("Error:", err);
          }
        };
        return $.ajax(settings);
      }
    });
  });

}).call(this);
