// Generated by CoffeeScript 1.4.0
(function() {
  var personTest;

  personTest = null;

  $(document).ready(function() {
    $('.nameInput').on("keyup", function(event) {
      var settings;
      if (event.keyCode === 13) {
        settings = {
          url: "/dbpedia/?wikipage=" + event.target.value,
          dataType: "json",
          success: function(data) {
            if (data.name) {
              personTest = data;
              $(".result").html("");
              return $(".result").append("<p>Person Name: " + personTest.name + "<br>Date of Birth: " + personTest.dob + "<br>URL: " + personTest.url + "<br>Relations: " + personTest.relations + "</p>");
            } else {
              return $(".result").append("<p>Not a Person</p>");
            }
          },
          error: function(err) {
            return console.log("Error:", err);
          }
        };
        return $.ajax(settings);
      }
    });
    return $('.findBirthDate').on("click", function(event) {
      return findBirthDate($(".nameInput").val(), function(birth) {
        $(".result").html("");
        return $(".result").append(birth);
      });
    });
  });

}).call(this);
