// Generated by CoffeeScript 1.4.0
(function() {
  var makeScraper;

  makeScraper = function() {
    var scraper;
    scraper = {
      getRelatedPeople: function(person) {
        return this.getDBPediaData(person);
      },
      checkIfPerson: function(link) {},
      getDBPediaData: function(pageTitle) {
        var options;
        options = {
          headers: {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE",
            "Access-Control-Allow-Headers": "Authorization"
          },
          url: "http://dbpedia.org/resource/" + pageTitle,
          dataType: "jsonp",
          error: function(error) {
            debugger;            return console.log("Error", error);
          },
          success: function(data) {
            return console.log("data: ", data);
          }
        };
        return $.ajax(options);
      }
    };
    return scraper;
  };

}).call(this);
