// Generated by CoffeeScript 1.4.0
(function() {

  define("typeAhead", function() {
    var attachWikiAutoComplete;
    return attachWikiAutoComplete = function(element) {
      return $(element).autocomplete({
        source: function(request, response) {
          return {
            url: "http://en.wikipedia.org/w/api.php",
            dataType: "jsonp",
            data: {
              'action': "opensearch",
              'format': "json",
              'search': request.term
            },
            success: function(data) {
              return response(data[1]);
            }
          };
        }
      });
    };
  });

}).call(this);
