// Generated by CoffeeScript 1.4.0
(function() {

  define("typeAhead", ["findBirth"], function(findBirth) {
    var attachWikiAutoComplete;
    attachWikiAutoComplete = function(element) {
      return $(element).autocomplete({
        source: function(request, response) {
          if (request.term.length > 1) {
            return $.ajax({
              url: "http://en.wikipedia.org/w/api.php",
              dataType: "jsonp",
              data: {
                'action': "opensearch",
                'format': "json",
                'search': request.term
              },
              success: function(data) {
                return response(data[1]);
              }
            });
          }
        }
      });
    };
    return {
      attachWikiAutoComplete: attachWikiAutoComplete
    };
  });

}).call(this);
