// Generated by CoffeeScript 1.4.0

define(function() {
  return {
    dist: function(a, b) {
      var xd, yd;
      xd = a.x - b.x;
      yd = a.y - b.y;
      return Math.sqrt(xd * xd + yd * yd);
    },
    mirror: function(f) {
      if ("function" !== typeof f) {
        f = d3.ease.apply(d3, arguments);
      }
      return function(t) {
        if (t < .5) {
          return f(2 * t);
        } else {
          return f(2 - 2 * t);
        }
      };
    },
    rand_c: function() {
      return '#' + (0x1000000 + (Math.random()) * 0xffffff).toString(16).substr(1, 6);
    }
  };
});
