// Generated by CoffeeScript 1.4.0
(function() {
  var request;

  request = require('request');

  exports.getJSON = function(wikipage, callBack) {
    var options;
    options = {
      url: "http://dbpedia.org/resource/" + wikipage,
      headers: {
        "Content-type": "application/json"
      }
    };
    return request(options, function(err, res, body) {
      if (err) {
        console.log("Error:", err);
      }
      console.log("Body", body);
      return callBack(body);
    });
  };

}).call(this);
