// Generated by CoffeeScript 1.4.0
(function() {
  var isPerson, models, request;

  request = require('request');

  models = require('./models');

  isPerson = function(data) {
    return data;
  };

  exports.getJSON = function(wikipage, callBack) {
    var options;
    options = {
      url: "http://dbpedia.org/resource/" + wikipage,
      headers: {
        "Accept": "application/json"
      }
    };
    return request(options, function(err, res, body) {
      var newPerson;
      if (err) {
        console.log("Error:", err);
      }
      console.log("Body", body);
      if (isPerson(JSON.parse(body))) {
        newPerson = models.makePerson(wikipage, new Date(), "http://en.wikipedia.org/" + wikipage);
        return callBack(true, newPerson);
      } else {
        return callBack(false);
      }
    });
  };

}).call(this);
