// Generated by CoffeeScript 1.4.0
(function() {
  var request;

  request = require('request');

  exports.getJSON = function(wikipage) {
    var options;
    options = {
      url: "http://dbpedia.org/resource/" + wikipage,
      headers: {
        "Content-type": "application/json"
      }
    };
    return request(options, function(err, res, body) {
      console.log(body);
      return body;
    });
  };

}).call(this);
