// Generated by CoffeeScript 1.4.0
(function() {

  exports.makePerson = function(name, dob, url) {
    var person;
    person = {
      name: name,
      dob: dob,
      url: url,
      relations: null
    };
    return person;
  };

}).call(this);
