// Generated by CoffeeScript 1.4.0

exports.makePerson = function(name, dob, url) {
  var person;
  person = {
    name: name,
    dob: dob,
    url: url,
    relations: null
  };
  return person;
};
