// Generated by CoffeeScript 1.4.0
(function() {
  var Person, db, mongoose, personSchema, pwd, url, user;

  mongoose = require('mongoose');

  user = process.env.mongoUser;

  pwd = process.env.mongoPWD;

  url = process.env.mongoDBURL;

  mongoose.connect("mongodb://" + user + ":" + pwd + "@" + url);

  db = mongoose.connection;

  db.once('open', function() {
    return console.log("Connection Open");
  });

  personSchema = mongoose.Schema({
    name: String,
    url: String,
    dob: String,
    relations: []
  });

  Person = mongoose.model("Person", personSchema);

  exports.addPerson = function(person, callBack) {
    var newPerson;
    newPerson = new Person({
      name: person.name,
      url: person.url,
      dob: person.dob,
      relations: person.relations
    });
    return newPerson.save(function(err) {
      if (err) {
        callBack(err);
      }
      return callBack();
    });
  };

  exports.getPerson = function(personName, callBack) {
    return Person.findOne({
      name: personName
    }, callBack);
  };

  exports.updatePersonRelations = function(name, relations, callBack) {
    return Person.findOneAndUpdate({
      name: name
    }, {
      relations: relations
    }, callBack);
  };

}).call(this);
